---
title: "Linking RStudio with GitHub for Version Control"
output: html_notebook
---

```{r}
#HAHA EDIT FOR PUSHING

##Link R with git so I can add version control to RStudio. 
#This will allow me to push code directly from RStudio that uploads onto GitHub online AND have multiple versions of my code saved so I can go back in my coding history.

#Make sure you have these three things before following the rest of the steps
#1. Install Rstudio to your computer
#2. Create an account on GitHub online
#3. Install Git to your computer (this is different from GitHub) -- find directions for this at https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

#The following steps are adapted from https://nceas.github.io/oss-lessons/version-control/4-getting-started-with-git-in-RStudio.html

```

```{r}
##Make local Git repository on your computer

#A repository (repo) is where all of your version controlled files are saved. On your computer, this looks like a single file folder that is dedicated to only saving code.
  #Create this folder now that is saved somewhere on your computer
  #Save this document in the folder you created

#Open up the terminal on your computer, copy/paste, and run the following code:
$ cd .../LinkToFolder
$ git init 
#Where .../LinkToFolder is the folder path to the repository folder you just created. You may need to google how to copy a folder path for your computer type (Macs and Windows are very different) if you haven't done this before.

#Extra info - The folder when one initialises the repository needs not necessarily need to be empty. It can be either empty or a folder with several different types of files. The git init command creates a hidden folder within the folder you just created which purpose is to keep track of all files in the directory.

```

```{r}
##Activate version control in RStudio

#Open RStudio
#Go to: Tools → Global Options, then click Git/SVN from the sidebar
  #If you already have Git installed, very likely in the field Git executable will appear the path where Git is installed in your computer. I leave this as-is (though you could change it if you know what you're doing)

#Select the box: Enable version control interface for RStudio projects at the top of the window and after that click the “Apply” and then "Ok" buttons at the bottom of the dialog window.
#Close the box and restart RStudio
```

```{r}
##Create a directory in RStudio

#Open RStudio and select "create a project" (the blue cube with the green plus in the top ribbon, second icon over from the left)
#A dialog window will open. Select "Existing Directory"
#You will see a new window. Click "Browse" and find the folder you created at the beginning of these steps
#click “Create Project”. After that, the project is created as a Git repository.
```

```{r}
##How to stage and commit

#Now that you have enabled git versioning for your Project, a “Git” tab should have been added to your interface next to “Environment” and “History” tabs in the upper right of the computer. You may have to drag the window out wider to see this.

#you should see the name of this file (i.e. SetUpGit.Rmd) and a .gitignore file. .gitignore is auto generated by R studio and hides all of the files we want to ignore and not track using version control. We will use this in the future.

#To begin tracking version control for a file (aka staging) check the "staged" box in front of the file name in the Git tab on the right
  #Check the .Rmd file for this doc (i.e SetupGit.Rmd)
  #Staging will be availible for any files you have saved in this directory (this folder)

#Now we commit the file (aka taking a snapshot of our work progress)
  #Hit the commit button in the banner above the file name you just checked - the icon is the white boxes with the green checkmark
  #May have to make the box wider to see the commit button
  #A new window will pop up
  #Write a description of the changes you made in the upper right and click commit
  #Close the window
  #That file will be gone from the list of files under the git tab (until you made more changes to the file)

#If you don't want to track changes for a file (for example, the .html version of this file), select the staged box for that file, click commit, and then in the popup window select "ignore" from the top banner instead of commit

#Note the ways to see version control for a file -- through the sideways Git button that is grey, red, and green at the top of the banner. Click the carrot to access the drop down, and there are "diff," log," and "revert" buttons.

#You should also see the name of the folder you created listed in the far upper right corner. This shows the directory (folder) you are saving your work in, so for example if you set up multiple version controlled folders for different projects, you could toggle between directories

```

```{r}
##Remote version control

#Everything above deals with LOCAL version control (using Git on your computer), but does not upload anything to online GitHub. We want to be able to upload our code online! You may notice that the arrows (pull/push) buttons on the Git tab are greyed out. The reason is that we did not tell RStudio to use any remote repository like those in GitHub.

#To activate pull/push buttons, it is necessary first to use the terminal to add a remote origin with the push command or pull a repository from GitHub.

#Now create a new repository on GitHub. I use the same name as the folder I made on my laptop. When you create a new repository, there will be a window with "Quick setup — if you’ve done this kind of thing before" and a url below. Copy the URL and paste it somewhere on your computer for the duration of this exercise, because the URL will go away.

#Go to the terminal and type in the command line
$ git remote add origin URL
#where URL means the full link of the repository on GitHub that you copied.

#Once you press enter for the command line above, very likely a dialog window will appear and you will be asked to enter some GitHub credentials like the username or password or both - READ BELOW BEFORE CONTINUING
  #While the terminal will ask for a password, GitHub changed security features in 2021 so instead of a password you need to enter a security token rather than your GitHub password.

#From https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
#To get a security token, click you profile icon in the top of right corner of the GitHub page and select settings
#In the left sidebar, select "developer settings"
#In the left sidebar, select "personal access tokens" and "Tokens (classic)"
#Select Generate new token, then click Generate new token (classic).
#In the "Note" field, give your token a descriptive name.
#To give your token an expiration, select Expiration, then choose a default option.
#Select the scopes you'd like to grant this token. Select repo (the first check box)
#Click Generate token.
#Copy the token address and paste it somewhere for the duration of this excercise - the token code goes away, and you may need to access it again!

#Go back to the terminal and if it asks for a password, use the token code instead of a password.

#The next command line to push the local repository to GitHub that you need to write in the terminal:
$ git push --set-upstream origin master
or
$ git push -u origin master

#After you enter the above push command, your local repository has been pushed to GitHub and one can directly check it by looking at the proper GitHub account. You should see some files appear in the repo you just made on GitHub. The push/pull arrows in RStudio should also be blue and green now.
```

```{r}
##Pulling from GitHub -- I never use this

#Once you have committed all changes to a file you are working on in RStudio, you can pull the latest version of the repository from GitHub by clicking on the pull button (in the same banner as commit). Conflict may happen during this steps if several persons have modified the same file. Don’t worry, git will walk you through the necessary steps to fix the conflicts.

#I never use this as I primarily work on my own code (not developing code in a team)
```

```{r}
##Pushing to GitHub -- This one I use all the time!

#You can click on the push button to upload your changes to GitHub and share your work with others. It's good practice to do this because it backs up the version control you have on your computer to online.
```

